# Data Wrangling with SQL

## Prepare Data

### Connect

In [19]:
# import libraries
import sqlite3
from sqlalchemy import create_engine
from sqlalchemy import inspect
from sqlalchemy.sql import text
import pandas as pd

In [3]:
# Load data files
building_structure = pd.read_csv('data/csv_building_structure.csv')
building_damage = pd.read_csv('data/csv_building_damage_assessment.csv')
household_demo = pd.read_csv('data/csv_household_demographics.csv')
mapping = pd.read_csv('data/mapping.csv')

/var/folders/t_/pmlbvsqs75j42mbfr3nngl940000gn/T/ipykernel_85533/958795357.py:3: DtypeWarning: Columns (17,29,34,35,36,37,38,39,40,41,42,47,50) have mixed types. Specify dtype option on import or set low_memory=False.
  building_damage = pd.read_csv('data/csv_building_damage_assessment.csv')

In [4]:
# create database
connection = sqlite3.connect('nepal_earthquake.db')

In [5]:
# load df tp sql db
building_damage.to_sql('building_damage', connection, if_exists='replace')
building_structure.to_sql('building_structure', connection, if_exists='replace')
household_demo.to_sql('household_demo', connection, if_exists='replace')
mapping.to_sql('mapping', connection, if_exists='replace')

3677133

### Explore

In [6]:
# Create engine: engine
engine = create_engine('sqlite:////Users/Blurryface/Documents/GitHub/Data_Science_Portfolio/4_Earthequake_Prediction/nepal_earthquake.db')

# Inspect DB for list of table names
insp = inspect(engine)

In [7]:
# Save the table names to a list: table_names
table_names = insp.get_table_names()

# Print the table names to the shell
print(table_names)

['building_damage', 'building_structure', 'household_demo', 'mapping']

In [24]:
# Open engine in context manager
# Perform query and save results to DataFrame: df
sql = """
    SELECT *
    FROM building_damage
    LIMIT 5;
"""
with engine.connect() as conn:
    query = conn.execute(text(sql))         
df = pd.DataFrame(query.fetchall())
# Print the head of the DataFrame df
print(df.head())

   index   building_id  district_id  vdcmun_id  ward_id  \
0      0  120101000011           12       1207   120703
1      1  120101000021           12       1207   120703
2      2  120101000031           12       1207   120703
3      3  120101000041           12       1207   120703
4      4  120101000051           12       1207   120703

  damage_overall_collapse damage_overall_leaning  \
0          Moderate-Heavy    Insignificant/light
1          Severe-Extreme         Severe-Extreme
2          Moderate-Heavy         Moderate-Heavy
3          Moderate-Heavy         Moderate-Heavy
4     Insignificant/light                   None

  damage_overall_adjacent_building_risk damage_foundation_severe  \
0                                  None                     None
1                   Insignificant/light    Severe-Extreme-(>2/3)
2                        Moderate-Heavy                     None
3                        Moderate-Heavy                     None
4                                  None                     None

  damage_foundation_moderate  ... has_damage_parapet  \
0      Moderate-Heavy-(<1/3)  ...                0.0
1                       None  ...                0.0
2      Moderate-Heavy-(>2/3)  ...                0.0
3      Moderate-Heavy-(>2/3)  ...                0.0
4                       None  ...                0.0

  has_damage_cladding_glazing has_geotechnical_risk  \
0                         0.0                   0.0
1                         0.0                   0.0
2                         0.0                   0.0
3                         0.0                   0.0
4                         0.0                   0.0

  has_geotechnical_risk_land_settlement has_geotechnical_risk_fault_crack  \
0                                     0                                 0
1                                     0                                 0
2                                     0                                 0
3                                     0                                 0
4                                     0                                 0

  has_geotechnical_risk_liquefaction has_geotechnical_risk_landslide  \
0                                  0                               0
1                                  0                               0
2                                  0                               0
3                                  0                               0
4                                  0                               0

  has_geotechnical_risk_rock_fall has_geotechnical_risk_flood  \
0                               0                           0
1                               0                           0
2                               0                           0
3                               0                           0
4                               0                           0

  has_geotechnical_risk_other
0                           0
1                           0
2                           0
3                           0
4                           0

[5 rows x 80 columns]

In [ ]:
# Perform query and save results to DataFrame: df
with engine.connect() as con:
    rs = con.execute("""
                 SELECT COUNT(*) AS Number_of_Observations
                 FROM building_damage
                 """)
    df = pd.DataFrame(rs.fetchall())
    df.columns = rs.keys()

# Print the head of the DataFrame df
print(df.head())

   Number_of_Observations
0                  762106

In [ ]:
# Perform query and save results to DataFrame: df
with engine.connect() as con:
    rs = con.execute("""
                 SELECT DISTINCT(district_id) AS Unique_Districts
                 FROM building_damage
                 """)
    df = pd.DataFrame(rs.fetchall())
    df.columns = rs.keys()

# Print the head of the DataFrame df
print(df.head())

   Unique_Districts
0                12
1                20
2                21
3                22
4                23

In [ ]:
# Perform query and save results to DataFrame: df
with engine.connect() as con:
    rs = con.execute("""
                 SELECT COUNT(DISTINCT(building_id)) AS Number_Of_Unique_Buildings
                 FROM building_damage
                 """)
    df = pd.DataFrame(rs.fetchall())
    df.columns = rs.keys()

# Print the head of the DataFrame df
print(df.head())

   Number_Of_Unique_Buildings
0                      762106

In [ ]:
# Show buildings in Okhaldhunga (District 12)
with engine.connect() as con:
    rs = con.execute("""
                 SELECT *
                 FROM building_damage
                 WHERE district_id = 12
                 LIMIT 5
                 """)
    df = pd.DataFrame(rs.fetchall())
    df.columns = rs.keys()

# Print the head of the DataFrame df
print(df.head())

   index   building_id  district_id  vdcmun_id  ward_id  \
0      0  120101000011           12       1207   120703
1      1  120101000021           12       1207   120703
2      2  120101000031           12       1207   120703
3      3  120101000041           12       1207   120703
4      4  120101000051           12       1207   120703

  damage_overall_collapse damage_overall_leaning  \
0          Moderate-Heavy    Insignificant/light
1          Severe-Extreme         Severe-Extreme
2          Moderate-Heavy         Moderate-Heavy
3          Moderate-Heavy         Moderate-Heavy
4     Insignificant/light                   None

  damage_overall_adjacent_building_risk damage_foundation_severe  \
0                                  None                     None
1                   Insignificant/light    Severe-Extreme-(>2/3)
2                        Moderate-Heavy                     None
3                        Moderate-Heavy                     None
4                                  None                     None

  damage_foundation_moderate  ... has_damage_parapet  \
0      Moderate-Heavy-(<1/3)  ...                0.0
1                       None  ...                0.0
2      Moderate-Heavy-(>2/3)  ...                0.0
3      Moderate-Heavy-(>2/3)  ...                0.0
4                       None  ...                0.0

  has_damage_cladding_glazing has_geotechnical_risk  \
0                         0.0                   0.0
1                         0.0                   0.0
2                         0.0                   0.0
3                         0.0                   0.0
4                         0.0                   0.0

  has_geotechnical_risk_land_settlement has_geotechnical_risk_fault_crack  \
0                                     0                                 0
1                                     0                                 0
2                                     0                                 0
3                                     0                                 0
4                                     0                                 0

  has_geotechnical_risk_liquefaction has_geotechnical_risk_landslide  \
0                                  0                               0
1                                  0                               0
2                                  0                               0
3                                  0                               0
4                                  0                               0

  has_geotechnical_risk_rock_fall has_geotechnical_risk_flood  \
0                               0                           0
1                               0                           0
2                               0                           0
3                               0                           0
4                               0                           0

  has_geotechnical_risk_other
0                           0
1                           0
2                           0
3                           0
4                           0

[5 rows x 80 columns]

In [ ]:
# Show the number of buildings in District 12
with engine.connect() as con:
    rs = con.execute("""
                 SELECT COUNT(*) AS Number_Of_Observations_D12
                 FROM building_damage
                 WHERE district_id = 12
                 """)
    df = pd.DataFrame(rs.fetchall())
    df.columns = rs.keys()

# Print the head of the DataFrame df
print(df.head())

   Number_Of_Observations_D12
0                       39352

In [ ]:
# Show the number of buildings in District 12
with engine.connect() as con:
    rs = con.execute("""
                 SELECT COUNT(DISTINCT(building_id)) AS Unique_Buildings_Okhaldhunga
                 FROM building_damage
                 WHERE district_id = 12
                 """)
    df = pd.DataFrame(rs.fetchall())
    df.columns = rs.keys()

# Print the head of the DataFrame df
print(df.head())

   Unique_Buildings_Okhaldhunga
0                         39352

In [ ]:
# Show the number of buildings in District 12
with engine.connect() as con:
    rs = con.execute("""
                 SELECT *
                 FROM building_structure
                 LIMIT 5
                  """)
    df = pd.DataFrame(rs.fetchall())
    df.columns = rs.keys()

# Print the head of the DataFrame df
print(df.head())

   index   building_id  district_id  vdcmun_id  ward_id  count_floors_pre_eq  \
0      0  120101000011           12       1207   120703                    1
1      1  120101000021           12       1207   120703                    1
2      2  120101000031           12       1207   120703                    1
3      3  120101000041           12       1207   120703                    1
4      4  120101000051           12       1207   120703                    1

   count_floors_post_eq  age_building  plinth_area_sq_ft  height_ft_pre_eq  \
0                     1             9                288                 9
1                     1            15                364                 9
2                     1            20                384                 9
3                     1            20                312                 9
4                     1            30                308                 9

   ...  has_superstructure_mud_mortar_brick  \
0  ...                                    0
1  ...                                    0
2  ...                                    0
3  ...                                    0
4  ...                                    0

  has_superstructure_cement_mortar_brick has_superstructure_timber  \
0                                      0                         0
1                                      0                         0
2                                      0                         0
3                                      0                         0
4                                      0                         0

  has_superstructure_bamboo has_superstructure_rc_non_engineered  \
0                         1                                    0
1                         1                                    0
2                         0                                    0
3                         0                                    0
4                         0                                    0

  has_superstructure_rc_engineered has_superstructure_other  \
0                                0                        0
1                                0                        0
2                                0                        0
3                                0                        0
4                                0                        0

           condition_post_eq  damage_grade  technical_solution_proposed
0       Damaged-Used in risk       Grade 3                 Major repair
1  Damaged-Repaired and used       Grade 5               Reconstruction
2  Damaged-Repaired and used       Grade 2                 Minor repair
3  Damaged-Repaired and used       Grade 2                 Minor repair
4  Damaged-Repaired and used       Grade 1                 Minor repair

[5 rows x 32 columns]

In [ ]:
# Show the number of buildings in District 12
with engine.connect() as con:
    rs = con.execute("""
                 SELECT COUNT(*) AS Number_Of_Buildings
                 FROM building_structure
                  """)
    df = pd.DataFrame(rs.fetchall())
    df.columns = rs.keys()

# Print the head of the DataFrame df
print(df.head())

   Number_Of_Buildings
0               762106

In [ ]:
# Show the only buildings in District 12
with engine.connect() as con:
    rs = con.execute("""
                 SELECT *
                 FROM mapping AS m
                 JOIN building_structure AS s ON m.building_id = s.building_id
                 WHERE district_id = 12
                 LIMIT 5
                  """)
    df = pd.DataFrame(rs.fetchall())
    df.columns = rs.keys()

# Print the head of the DataFrame df
print(df.head())

     index      individual_id    household_id   building_id  index  \
0  2302329  12010100001101001  12010100001101  120101000011      0
1  2302330  12010100001101002  12010100001101  120101000011      0
2  2302331  12010100001101003  12010100001101  120101000011      0
3  1610928  12010100002101001  12010100002101  120101000021      1
4  1610929  12010100002101002  12010100002101  120101000021      1

    building_id  district_id  vdcmun_id  ward_id  count_floors_pre_eq  ...  \
0  120101000011           12       1207   120703                    1  ...
1  120101000011           12       1207   120703                    1  ...
2  120101000011           12       1207   120703                    1  ...
3  120101000021           12       1207   120703                    1  ...
4  120101000021           12       1207   120703                    1  ...

   has_superstructure_mud_mortar_brick  \
0                                    0
1                                    0
2                                    0
3                                    0
4                                    0

   has_superstructure_cement_mortar_brick  has_superstructure_timber  \
0                                       0                          0
1                                       0                          0
2                                       0                          0
3                                       0                          0
4                                       0                          0

   has_superstructure_bamboo  has_superstructure_rc_non_engineered  \
0                          1                                     0
1                          1                                     0
2                          1                                     0
3                          1                                     0
4                          1                                     0

  has_superstructure_rc_engineered has_superstructure_other  \
0                                0                        0
1                                0                        0
2                                0                        0
3                                0                        0
4                                0                        0

           condition_post_eq damage_grade technical_solution_proposed
0       Damaged-Used in risk      Grade 3                Major repair
1       Damaged-Used in risk      Grade 3                Major repair
2       Damaged-Used in risk      Grade 3                Major repair
3  Damaged-Repaired and used      Grade 5              Reconstruction
4  Damaged-Repaired and used      Grade 5              Reconstruction

[5 rows x 36 columns]

In [ ]:
# Show the buildings in district 12
with engine.connect() as con:
    rs = con.execute("""
                 SELECT DISTINCT(m.building_id) AS b_id, s.*
                 FROM mapping AS m
                 JOIN building_structure AS s ON m.building_id = s.building_id
                 WHERE district_id = 12
                 LIMIT 5
                  """)
    df = pd.DataFrame(rs.fetchall())
    df.columns = rs.keys()

# Print the head of the DataFrame df
print(df.head())

           b_id  index   building_id  district_id  vdcmun_id  ward_id  \
0  120101000011      0  120101000011           12       1207   120703
1  120101000021      1  120101000021           12       1207   120703
2  120101000031      2  120101000031           12       1207   120703
3  120101000041      3  120101000041           12       1207   120703
4  120101000051      4  120101000051           12       1207   120703

   count_floors_pre_eq  count_floors_post_eq  age_building  plinth_area_sq_ft  \
0                    1                     1             9                288
1                    1                     1            15                364
2                    1                     1            20                384
3                    1                     1            20                312
4                    1                     1            30                308

   ...  has_superstructure_mud_mortar_brick  \
0  ...                                    0
1  ...                                    0
2  ...                                    0
3  ...                                    0
4  ...                                    0

   has_superstructure_cement_mortar_brick has_superstructure_timber  \
0                                       0                         0
1                                       0                         0
2                                       0                         0
3                                       0                         0
4                                       0                         0

  has_superstructure_bamboo has_superstructure_rc_non_engineered  \
0                         1                                    0
1                         1                                    0
2                         0                                    0
3                         0                                    0
4                         0                                    0

  has_superstructure_rc_engineered has_superstructure_other  \
0                                0                        0
1                                0                        0
2                                0                        0
3                                0                        0
4                                0                        0

           condition_post_eq damage_grade  technical_solution_proposed
0       Damaged-Used in risk      Grade 3                 Major repair
1  Damaged-Repaired and used      Grade 5               Reconstruction
2  Damaged-Repaired and used      Grade 2                 Minor repair
3  Damaged-Repaired and used      Grade 2                 Minor repair
4  Damaged-Repaired and used      Grade 1                 Minor repair

[5 rows x 33 columns]

In [17]:
sql = '''
    SELECT DISTINCT(m.building_id) AS b_id, 
           s.*,
           d.damage_grade
    FROM mapping AS m
    JOIN building_structure AS s ON m.building_id = s.building_id
    JOIN building_damage AS d ON m.building_id = d.building_id
    WHERE s.district_id = 12
    LIMIT 5;
'''

with engine.connect() as conn:
    query = conn.execute(text(sql))         
df = pd.DataFrame(query.fetchall())
# Print the head of the DataFrame df
print(df.head())

           b_id  index   building_id  district_id  vdcmun_id  ward_id  \
0  120101000011      0  120101000011           12       1207   120703
1  120101000021      1  120101000021           12       1207   120703
2  120101000031      2  120101000031           12       1207   120703
3  120101000041      3  120101000041           12       1207   120703
4  120101000051      4  120101000051           12       1207   120703

   count_floors_pre_eq  count_floors_post_eq  age_building  plinth_area_sq_ft  \
0                    1                     1             9                288
1                    1                     1            15                364
2                    1                     1            20                384
3                    1                     1            20                312
4                    1                     1            30                308

   ...  has_superstructure_cement_mortar_brick  has_superstructure_timber  \
0  ...                                       0                          0
1  ...                                       0                          0
2  ...                                       0                          0
3  ...                                       0                          0
4  ...                                       0                          0

  has_superstructure_bamboo has_superstructure_rc_non_engineered  \
0                         1                                    0
1                         1                                    0
2                         0                                    0
3                         0                                    0
4                         0                                    0

  has_superstructure_rc_engineered has_superstructure_other  \
0                                0                        0
1                                0                        0
2                                0                        0
3                                0                        0
4                                0                        0

           condition_post_eq  damage_grade technical_solution_proposed  \
0       Damaged-Used in risk       Grade 3                Major repair
1  Damaged-Repaired and used       Grade 5              Reconstruction
2  Damaged-Repaired and used       Grade 2                Minor repair
3  Damaged-Repaired and used       Grade 2                Minor repair
4  Damaged-Repaired and used       Grade 1                Minor repair

   damage_grade
0       Grade 3
1       Grade 5
2       Grade 2
3       Grade 2
4       Grade 1

[5 rows x 34 columns]

### Import

In [20]:
query = '''
    SELECT DISTINCT(m.building_id) AS b_id, 
           s.*,
           d.damage_grade
    FROM mapping AS m
    JOIN building_structure AS s ON m.building_id = s.building_id
    JOIN building_damage AS d ON m.building_id = d.building_id
    WHERE s.district_id = 12
    LIMIT 5;
'''

print(query)

    SELECT DISTINCT(m.building_id) AS b_id,
           s.*,
           d.damage_grade
    FROM mapping AS m
    JOIN building_structure AS s ON m.building_id = s.building_id
    JOIN building_damage AS d ON m.building_id = d.building_id
    WHERE s.district_id = 12
    LIMIT 5;

In [22]:
df = pd.read_sql_query(query, connection, index_col='b_id')
df.head()

,index,building_id,district_id,vdcmun_id,ward_id,count_floors_pre_eq,count_floors_post_eq,age_building,plinth_area_sq_ft,height_ft_pre_eq,...,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,condition_post_eq,damage_grade,technical_solution_proposed,damage_grade
b_id,,,,,,,,,,,,,,,,,,,,,
120101000011,0,120101000011,12,1207,120703,1,1,9,288,9,...,0,0,1,0,0,0,Damaged-Used in risk,Grade 3,Major repair,Grade 3
120101000021,1,120101000021,12,1207,120703,1,1,15,364,9,...,0,0,1,0,0,0,Damaged-Repaired and used,Grade 5,Reconstruction,Grade 5
120101000031,2,120101000031,12,1207,120703,1,1,20,384,9,...,0,0,0,0,0,0,Damaged-Repaired and used,Grade 2,Minor repair,Grade 2
120101000041,3,120101000041,12,1207,120703,1,1,20,312,9,...,0,0,0,0,0,0,Damaged-Repaired and used,Grade 2,Minor repair,Grade 2
120101000051,4,120101000051,12,1207,120703,1,1,30,308,9,...,0,0,0,0,0,0,Damaged-Repaired and used,Grade 1,Minor repair,Grade 1